services:
  watchtower:
    image: containrrr/watchtower
    container_name: 'watchtower'
    restart: 'unless-stopped'
    environment:
      TZ: America/New_York
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_ROLLING_RESTARTING: true
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: "Ubuntu2-2504-dockerapps Server"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: user@domain.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: user@domain.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: mail.domain.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: user@domain.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "password"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
