version: "3.9"

services:
  headscale:
    image: headscale/headscale:v0.23.0-alpha12
    container_name: headscale
    restart: unless-stopped
    ports:
    - 8080:8080
    - 9090:9090
    environment:
      - TZ=Europe/London
    volumes:
      - ./conf:/etc/headscale
      - headscale-data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      - proxy
      traefik.udp.services.headscale-udp-41641.loadbalancer.server.port: 41641
      traefik.udp.services.headscale-udp-3478.loadbalancer.server.port: 3478

  headscale-admin:
    image: goodieshq/headscale-admin:latest
    container_name: headscale-admin
    restart: unless-stopped
    ports:
      - 8085:80
    networks:
      - proxy

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    ports:
    8090:80
    container_name: headscale-ui
    networks:
      - proxy
networks:
  proxy:
    external: true

volumes:
  headscale-data: