---
services:
    it-tools:
        container_name: it-tools
        restart: unless-stopped
        ports:
            - '8089:80'
        image: 'corentinth/it-tools:latest' 
        deploy:
          mode: replicated
          replicas: 3
          placement:
            max_replicas_per_node: 1
        networks:
          - proxy
networks:
  proxy:
    external: true