services:
  # Adminer - Frontend for Various Databases (MariaDB, PostgreSQL, etc.)
  adminer:
    image: adminer:latest
    container_name: adminer
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080:8080"

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
