services:
  # CrowdSec - Open-source & Collaborative IPS
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    ports:
      - "$CROWDSEC_PORT:8080" # Local API port
      - "6060:6060" # Exposing metrics via Zerotier IP
    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux fulljackz/proxmox crowdsecurity/sshd"
      GID: $PGID
      CUSTOM_HOSTNAME: $HOSTNAME
    volumes:
      - $DOCKERDIR/logs/$HOSTNAME:/logs/$HOSTNAME:ro
      - /var/log:/var/log:ro
      - $DOCKERDIR/appdata/crowdsec/data:/var/lib/crowdsec/data
      - $DOCKERDIR/appdata/crowdsec/config:/etc/crowdsec