services:
  # Qdrant - A vector database and search engine
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    networks:
      - default
    ports:
      - 6333:6333 # HTTP API and dashboard
      - 6334:6334 # gRPC API
    volumes:
      - ./appdata/qdrant:/qdrant/storage
