---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "500:80/tcp"
    #  - "443:443/tcp"
    networks:
      pihole_internal:
        ipv4_address: 172.70.9.3
      pihole:
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'e6z1EBVDERIP7'
      PIHOLE_DNS_: '172.70.9.2#5053'
      DNSMASQ_LISTENING: 'all'
      VIRTUAL_HOST: pihole.mikemcfetridge.com
    volumes:
      - /home/miker/dockerapps/pihole/appdata/pihole/etc:/etc/pihole
      - /home/miker/dockerapps/pihole/appdata/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
      - /home/miker/dockerapps/pihole/appdata/pihole/log:/var/log/pihole
    restart: unless-stopped


networks:
  pihole_internal:
     ipam:
       config:
         - subnet: 172.70.9.0/29
     name: pihole_internal
  pihole:
    external: true