services:
  # Pi-hole - DNS Server and AdBlocker
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["all", "core"]
    networks:
      - default
    # cap_add:
    #   # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #   # Required if you are using Pi-hole as your DHCP server, else not needed
    #   - NET_ADMIN
    #   # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
    #   - SYS_TIME
    #   # Optional, if Pi-hole should get some more processing time
    #   - SYS_NICE
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # DHCP Server
      - "80:80/tcp" # HTTP
      # - "123:123/udp" # NTP
      # - "443:443" # HTTPS
    volumes:
      - "/home/miker/dockerapps/pihole/appdata/pihole/etc:/etc/pihole"
      - "/home/miker/dockerapps/pihole/appdata/pihole/etc/dnsmasq.d:/etc/dnsmasq.d"
      - "/home/miker/dockerapps/pihole/appdata/pihole/log:/var/log/pihole"
    environment:
      # https://docs.pi-hole.net/docker/upgrading/v5-v6/?h=pihole_dns#misc Variables list for v6
      TZ: ${TZ}
      FTLCONF_webserver_api_password: !Sucyetat123
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: 9.9.9.9;1.1.1.1;192.168.2.5
      FTLCONF_dns_bogusPriv: "true"
      FTLCONF_dns_domainNeeded: "true"
      FTLCONF_dns_domain: home.mikemcfetridge
      FTLCONF_webserver_interface_theme: "default_dark"
    # DOCKER-LABELS-PLACEHOLDER