services:
  # Scrutiny - WebUI for smartd S.M.A.R.T monitoring
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
    ports:
      - $SCRUTINY_PORT:8080
    volumes:
      - $DOCKERDIR/appdata/scrutiny:/opt/scrutiny/config
    # DOCKER-LABELS-PLACEHOLDER