services:
  # Ombi - Media Requests for Plex and Emby
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$OMBI_PORT:3579"
    volumes:
      - $DOCKERDIR/appdata/ombi:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: /ombi #optional
    # DOCKER-LABELS-PLACEHOLDER