services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/miker/docker/emulatorjs/config:/config
      - /home/miker/docker/emulatorjs/rompack:/data
      - /home/miker/docker/emulatorjs/rompack/atari2600/roms:/data/atari2600/roms:ro
      - /home/miker/docker/emulatorjs/rompack/gba/roms:/data/gba/roms:ro
      - /home/miker/docker/emulatorjs/rompack/n64/roms:/data/n64/roms:ro
      - /home/miker/docker/emulatorjs/rompack/nes/roms:/data/nes/roms:ro
      - /home/miker/docker/emulatorjs/rompack/ngp/roms:/data/ngp/roms:ro
      - /home/miker/docker/emulatorjs/rompack/segaMD/roms:/data/segaMD/roms:ro
      - /home/miker/docker/emulatorjs/rompack/segaMS/roms:/data/segaMS/roms:ro
      - /home/miker/docker/emulatorjs/rompack/snes/rom:/data/snes/roms:ro
    ports:
      - 3000:3000
      - 8080:80
      - 4001:4001 #optional
    restart: unless-stopped
