version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "mmcfetridge"
      DB_MYSQL_PASSWORD: "!Sucyetat1"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /home/ubuntu/nginx-proxy-manager/data:/data
      - /home/ubuntu/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '!Sucyetat1'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'mmcfetridge'
      MYSQL_PASSWORD: '!Sucyetat1'
    volumes:
      - /home/ubuntu/nginx-proxy-manager/data/mysql:/var/lib/mysql

