---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=jellyfin.example.com
    volumes:
      - /home/miker/docker/jellyfin/data/config:/config
      - /home/miker/docker/jellyfin/data/tvshows:/data/tvshows
      - /home/miker/docker/jellyfin/data/movies:/data/movies
      - /home/miker/docker/jellyfin/data/music:/data/music
    ports:
      - 8096:8096
    restart: unless-stopped
