version: "3"

services:
  
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000/tcp" 
      - "9000:9000/tcp" 
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock' 
      - '/home/username/portainer/data:/data' 
    restart: unless-stopped
    
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "800:80/tcp"
    environment:
      TZ: 'America/new_york'
      WEBPASSWORD: 'adminadmin'   #need to change this password
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  nginx_proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment: #update the below with your DB name, username and password
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"  
    volumes:
      - /home/nginxproxy/data:/data
      - /home/nginxproxy/letsencrypt:/etc/letsencrypt
  Proxy_db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment: # copy this information from the above you created and add a root password
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /home/nginxproxy/mysql:/var/lib/mysql
    
  uptime-kuma: 
    container_name: uptime-kuma
    image: "louislam/uptime-kuma:1"
    ports: 
      - "3001:3001/tcp"
    restart: unless-stopped
    volumes: 
      - "/home/username/uptime-kuma:/app/data"

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/username/netdataconfig:/etc/netdata
      - /home/username/netdatalib:/var/lib/netdata
      - /home/username/netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

