# Sample yml template
#
version: '3'
services:
  uptime-kuma:
    container_name: (name you want displayed in docker/portainer)
    image: elestio/uptime-kuma
    environment:
      - DB_TYPE=sqlite
      - DB_STORAGE=/app/data/uptime-kuma.db
      - SOFTWARE_VERSION_TAG=latest
      - URL=https://kuma.mikeandrebel.com
    volumes:
      - /home/miker/docker/kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.kuma.entrypoints=websecure"
#      - "traefik.http.routers.kuma.rule=Host(`kuma.mikeandrebel.com`)"
#      - "traefik.http.routers.kuma.tls=true"
#      - "traefik.http.routers.kuma.tls.certresolver=staging"
#      - "traefik.http.services.gitlab.loadBalancer.server.port=3001"
    restart: always
    healthcheck:
      disable: true

# used to place in the NPM / traefik network so they can talk with each other.
    networks:
      - proxy
networks:
  proxy:
    external: true






    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.rule=Host(`authentik.mikeandrebel.com`)"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.tls.certresolver=staging"

      - "traefik.http.services.gitlab.loadBalancer.server.port=8941"


