services:
  # The Lounge - Self-hosted web IRC client
  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./appdata/thelounge:/config
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
    
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s