services:
  # The Lounge - Self-hosted web IRC client
  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$THELOUNGE_PORT:9000"
    volumes:
      - $DOCKERDIR/appdata/thelounge:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER