services:
  # NZBGet - Binary newsgrabber (NZB downloader)
  nzbget:
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "downloads", "all"]
    networks:
      - default
    ports:
      - "$NZBGET_PORT:6789" 
    volumes:
      - $DOCKERDIR/appdata/nzbget:/config
      - $DOWNLOADSDIR:/data/downloads
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      # NZBGET_USER: nzbget     #optional
      # NZBGET_PASS: tegbzn6789 #optional
    # DOCKER-LABELS-PLACEHOLDER