services:
  # qBittorrent - Torrent downloader
  qbittorrent-vpn:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-vpn
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "downloads", "all"]
    network_mode: "service:gluetun"
    volumes:
      - $DOCKERDIR/appdata/qbittorrent-vpn:/config
      - $DOWNLOADSDIR:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 002
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels: # Traefik labels added via file provider app-qbittorrent.yml in rules folder
      - "deunhealth.restart.on.unhealthy=true"