# SearxNG - Privacy-respecting Metasearch Engine
services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /home/miker/dockerapps/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://search.mikemcfetridge.com
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
