
services:
  trilium:
    image: zadam/trilium
    restart: always
    environment:
      - ./trilium/data=/home/node/trilium-data
    volumes:
      - ./trilium:/home/node/trilium-data
    ports:
      - 8180:8080

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
