services:
  # TriliumNext - Personal Heirarchical Notes
  triliumnext:
    image: triliumnext/notes:latest
    container_name: triliumnext
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$TRILIUMNEXT_PORT:8080"
    volumes:
      - $DOCKERDIR/appdata/triliumnext:/home/node/trilium-data
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - TZ=$TZ
    # DOCKER-LABELS-PLACEHOLDER
