services:
  # Vikunja - Task Management
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    depends_on:
      mariadb:
        condition: service_healthy
    user: $PUID
    ports:
      - "$VIKUNJA_PORT:3456"
    volumes:
      - $DOCKERDIR/appdata/vikunja:/app/vikunja/files
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://VIKUNJA-SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1
      VIKUNJA_DATABASE_HOST: mariadb
      VIKUNJA_DATABASE_PASSWORD: $VIKUNJA_MARIADB_PASSWORD
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: $VIKUNJA_MARIADB_USERNAME
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: $VIKUNJA_JWT_SECRET
    # DOCKER-LABELS-PLACEHOLDER
