services:
  # Maintainerr - Manage Plex Media
  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$MAINTAINERR_PORT:6246"
    user: $PUID:$PGID
    volumes:
      - $DOCKERDIR/appdata/maintainerr:/opt/data
    environment:
      TZ: $TZ
      DEBUG: true
    # DOCKER-LABELS-PLACEHOLDER