services:
  # GPTWOL - Wake On LAN Docker GUI
  gptwol:
    container_name: gptwol
    image: misterbabou/gptwol:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PORT=$GPTWOL_PORT # default port is 5000
      - REFRESH_PING=60 # in seconds
      # - PING_TIMEOUT=200 # in milliseconds
    volumes:
      - ./appdata/gptwol/computers.txt:/app/computers.txt
      - ./appdata/gptwol/cron:/etc/cron.d      
  

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
