  GNU nano 7.2                                                                                                 docker-compose.yml                                                                                                           
networks:
  proxy:
    external: true
  giteadb:
    external: true

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=giteaadmin
      - GITEA__database__PASSWD=5HGrjZETwVDI5WL0EY3v
    restart: always
    networks:
      - proxy
      - giteadb
    volumes:
      - /home/miker/docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "3000:3000"
#      - "222:22"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=5HGrjZETwVDI5WL0EY3v
      - MYSQL_USER=giteaadmin
      - MYSQL_PASSWORD=5HGrjZETwVDI5WL0EY3v
      - MYSQL_DATABASE=gitea
    networks:
      - giteadb
    volumes:
      - /home/miker/docker/gitea/mysql:/var/lib/mysql
