services:
  # Hemmelig - Secret Sharing Application
  hemmelig:
    image: hemmeligapp/hemmelig
    hostname: hemmelig
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$HEMMELIG_PORT:3000"
    healthcheck:
        test: 'wget -O /dev/null localhost:3000/api/healthz || exit 1'
        timeout: 5s
        retries: 3
    stop_grace_period: 1m
    init: true
    volumes:
      - $DOCKERDIR/appdata/hemmelig/files:/var/tmp/hemmelig/upload/files
      - $DOCKERDIR/appdata/hemmelig/database:/home/node/hemmelig/database
    environment:
        - SECRET_LOCAL_HOSTNAME=0.0.0.0 # The local hostname for the fastify instance
        - SECRET_PORT=3000 # The port number for the fastify instance
        - SECRET_HOST=$DOMAINNAME_1 # Used for i.e. set cors/cookies to your domain name
        - SECRET_ROOT_USER=$HEMMELIG_ROOT_USER # User as the root admin user
        - SECRET_ROOT_PASSWORD=$HEMMELIG_ROOT_PASSWORD # The admin user password (change this after signed in)
        - SECRET_ROOT_EMAIL=$HEMMELIG_ROOT_EMAIL # The email for the admin user
        - SECRET_FILE_SIZE=4 # Set the total allowed upload file size in mb
        - SECRET_FORCED_LANGUAGE=en # Set the default language for the application
        - SECRET_JWT_SECRET=$HEMMELIG_JWT_SECRET # Override this for the secret signin JWT tokens for log in
        - SECRET_MAX_TEXT_SIZE=256 # The max text size for the secret. Is set in kb. i.e. 256 for 256kb
    # DOCKER-LABELS-PLACEHOLDER