# Authelia

# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark #light/dark
jwt_secret: GdKg9KdDR1VHrkti097UEe2 #any text or number you want to add here to create jwt Token

default_redirection_url: https://auth.mikemcfetridge.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info

totp:
  issuer: mikemcfetridge.com #your authelia top-level domain
  period: 30
  skew: 1
  digits: 6

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    # Rules applid to everyone
    - domain:
        - "auth.mikemcfetridge.com" #This should be your authentication URL
      policy: bypass
    - domain:
        - "dashy.mikemcfetridge.com" #example domain to protect
#        -  "heimdall.mikemcfetridge.com" #example domain to protect
      policy: one_factor
    - domain:
        - "pve1.mikemcfetridge.com" # Proxmox Server
        - "proxy.mikemcfetridge.com" # Proxy Server
        - "port.mikemcfetridge.com" # Portainer Server
        - "pihole.mikemcfetridge.com" # PiHole
        - "vscode.mikemcfetridge.com" # VSCode Server
      policy: two_factor

      #add or remove additional subdomains as necessary. currenlty only supports ONE top-level domain
      #any time you add a new subdomain, you will need to restart the Authelia container to recognize the new settings/rules

session:
  name: authelia_session
  secret: MJ96GgfrIjMGFrew897qtpk #any text or number you want to add here to create jwt Token
  expiration: 3600  # 1 hour
  inactivity: 7200  # 2 hours
  domain: mikemcfetridge.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m


storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
  encryption_key: KJUdYtEbNHJdjdyr18Hy543 #added Dec 5 2021

notifier:
  filesystem:
    filename: /config/notifications.txt
  disable_startup_check: true #true/false
#  smtp:
#    username: mike@mcfetridge.us #your email address
#    password: !Sucyetat1 #your email password
#    host: mail.mcfetridge.us #email smtp server
#    port: 587 #email smtp port
#    sender: mike@mcfetridge.us
#    identifier: localhost
#    subject: "[Authelia] {title}" #email subject
#    startup_check_address: mike@mcfetridge.us
#    disable_require_tls: false
#    disable_html_emails: false
#    tls:
#      skip_verify: false
#      minimum_version: TLS1.2
...
