services:
  # Stirling PDF - Self-hosted PDF Manipulation
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
 
    ports:
      - "8080:8080" 
    volumes:
      - ./appdata/stirling-pdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./appdata/stirling-pdf/extraConfigs:/configs
      - ./appdata/stirling-pdf/customFiles:/customFiles/
      - ./appdata/stirling-pdf/logs:/logs/
    environment:
      DOCKER_ENABLE_SECURITY: false
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
      LANGS: en_US

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s