services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:2.3.0p7
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - ./checkmk/monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8000"
      - "8500:5000"
    restart: unless-stopped
    networks:
      checkmk_network:

networks:
    checkmk_network:

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
# When build is complete, you need to look in the logs for the default username and password.


