services:
  # CyberChef - Encryption, encoding, compression and data analysis
  cyberchef:
    image: mpepping/cyberchef:latest
    container_name: cyberchef
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8000:8000"

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

