services:
  # n8n - Workflow Automation Tool
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - $N8N_PORT:5678
    volumes:
      - $DOCKERDIR/appdata/n8n:/home/node/.n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${N8N_POSTGRESQL_USERNAME}
      - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRESQL_PASSWORD}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_EDITOR_BASE_URL=https://SUBDOMAIN-PLACEHOLDER.${DOMAINNAME_1}
      - WEBHOOK_URL=https://SUBDOMAIN-PLACEHOLDER.${DOMAINNAME_1}
    # DOCKER-LABELS-PLACEHOLDER
