services:
  # FunkWhale - Music Server
  funkwhale:
    container_name: funkwhale
    image: thetarkus/funkwhale
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - $FUNKWHALE_PORT:80
    volumes:
      - $DOCKERDIR/appdata/funkwhale:/data
      # - $MEDIADIR1:/data/media1
      # - $MEDIADIR2:/data/media2
      # - $MEDIADIR3:/data/media3
    environment:
      - PUID=$PUID
      - PGID=$PGID
      # - FUNKWHALE_HOSTNAME=$FUNKWHALE_SUBDOMAIN.$DOMAINNAME1
      # - NESTED_PROXY=1
    # DOCKER-LABELS-PLACEHOLDER