services:
  # VSCode - VSCode Editing
  vscode:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
    ports:
      - "$VSCODE_PORT:8443"
    volumes:
      - $DOCKERDIR/appdata/vscode:/config
      - $USERDIR:/data/$PRIMARY_USERNAME
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      # - DOCKER_HOST
      # - PASSWORD=$VSCODE_PASSWORD
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD= password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN= code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/data/User/Workspaces/Default.code-workspace #optional
    # DOCKER-LABELS-PLACEHOLDER
