services:
  # VSCode - VSCode Editing
  vscode:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - ./appdata/vscode:/config
      - ./appdata/data:/data/$PRIMARY_USERNAME
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      # - DOCKER_HOST
      # - PASSWORD=$VSCODE_PASSWORD
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD= password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN= code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/data/User/Workspaces/Default.code-workspace #optional

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
