services:
  # Weaviate - Vector Database
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    container_name: weaviate
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
     - "$WEAVIATE_PORT:8080"  # REST calls
     - "50051:50051"  # gRPC calls
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    volumes:
    - $DOCKERDIR/appdata/weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true' # Not secure but OK for local use
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
    # DOCKER-LABELS-PLACEHOLDER