services:
  # Transmission - Torrent downloader
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./transmission:/config
      - ./torrents:/data/downloads
      - ./Downloads:/data/watch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - FILE__USER=/run/secrets/transmission_user
      - FILE__PASS=/run/secrets/transmission_pass
      # - TRANSMISSION_WEB_HOME= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    secrets:
      - transmission_user
      - transmission_pass  

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s