version: '3.3'
services:
  gotify:
    image: gotify/server
    container_name: gotify
    volumes:
      - /home/ubuntu/docker/gotify:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - TZ=Europe/London
networks:
  proxy:
    external: true
