services:
  gotify:
    image: gotify/server
    container_name: gotify
    volumes:
      - ./gotify:/app/data
    restart: unless-stopped
#    ports:
#      - '8091:80'
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - TZ=America/New_York

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s