services:
  # SABnzbd - Binary newsgrabber (NZB downloader)
  # Disable SABNnzbd's built-in HTTPS support for traefik proxy to work
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8080:8080" 
    volumes:
      - ./sabnzbd:/config
      - ./Downloads:/data/downloads
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      UMASK_SET: 002

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s