services:
  # Redis - Key-value Store
  # Add vm.overcommit_memory = 1 to /etc/sysctl.conf
  redis:
    image: docker.io/library/redis:alpine
    container_name: redis
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command: --save 60 1 --loglevel warning
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - ./appdata/redis:/data

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
