services:
  # FreshRSS - RSS News Reader
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./appdata/freshrss:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
