services:
  # FreshRSS - RSS News Reader
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$FRESHRSS_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/freshrss:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    # DOCKER-LABELS-PLACEHOLDER
