services:
  # Jellyseerr - Media Requests and Discovery for Plex
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "5055:5055"
    volumes:
      - ./jellyseerr:/app/config
    environment:
      TZ: America/New_York
      LOG_LEVEL: info

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s