services:
  # Jellyseerr - Media Requests and Discovery for Plex
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$JELLYSEERR_PORT:5055"
    volumes:
      - $DOCKERDIR/appdata/jellyseerr:/app/config
    environment:
      TZ: $TZ
      LOG_LEVEL: info
    # DOCKER-LABELS-PLACEHOLDER