---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.jimsgarage.co.uk #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /home/ubuntu/docker/code-server/config:/config
    networks:
      proxy:

    restart: unless-stopped

networks:
  proxy:
    external: true
