services:
  # Redis Commander - Redis Management Tool
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "$REDISCOMMANDER_PORT:8081"
    environment:
      - REDIS_HOST=redis
      # - REDIS_PASSWORD=$REDIS_PASSWORD
    # DOCKER-LABELS-PLACEHOLDER