services:
  # Redis Commander - Redis Management Tool
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      # - REDIS_PASSWORD=$REDIS_PASSWORD

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
