services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: sqlite
      APP_KEY: $SPEEDTEST_TRACKER_APP_KEY #optional
      # DB_HOST: mariadb #optional
      # DB_PORT: 3306 #optional
      # DB_DATABASE: speedtest #optional
      # DB_USERNAME: speedtest_user #optional
      # DB_PASSWORD: ST-DB-PASSWORD-PLACEHOLDER #optional
    volumes:
      - ./appdata/speedtest-tracker:/config

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s