tcp:
  routers:
    HOST-PLACEHOLDER-rtr:
      entryPoints:
        - websecure-internal
        - websecure-external
      rule: "HostSNIRegexp(`DOMAINNAME-VARIABLE-PLACEHOLDER`) || HostSNIRegexp(`{subdomain:[a-z]+}.DOMAINNAME-VARIABLE-PLACEHOLDER`)"
      service: HOST-PLACEHOLDER-svc
      tls:
        passthrough: true
  services:
    HOST-PLACEHOLDER-svc:
      loadBalancer:
        servers:
          - address: "HOST-IP-PLACEHOLDER:443"