services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest  # Specifies the Mealie Docker i>
    container_name: mealie                      # Names the container for easier>
    restart: always
    ports:
      - "9925:9000"                             # Maps port 9925 on the host to >
    deploy:
      resources:
        limits:
          memory: 1000M                         # Limits the container to use a >
    volumes:
      - ./mealie/data:/app/data/                  # Persists data in>
      - ./config/addons_config/mealie/config.yaml:/config/config.yanl
    environment:
      - ALLOW_SIGNUP=false                      # Allows new user signups on the>
      - PUID=1000                               # Sets the user ID for the conta>
      - PGID=1000                               # Sets the group ID for the cont>
      - TZ=America/New_York                     # Sets the timezone for the cont>
      - MAX_WORKERS=1                           # Limits the number of workers t>
      - WEB_CONCURRENCY=1                       # Sets the concurrency level for>
      - BASE_URL=mealie.yourdomain.com      # The base URL where Mealie is a>
      # Email Settings
      - SMTP_HOST=mail.yourdomain.us
      - SMTP_PORT=587
      - SMTP_FROM_NAME=user@yourdomain.com
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_FROM_EMAIL=user@yourdomain.com
      - SMTP_USER=user@yourdomain.com
      - SMTP_PASSWORD=${EM_PASS}
      # OIDC Settings
#      - OIDC_AUTH_ENABLED=true
#      - OIDC_SIGNUP_ENABLED=true
#      - OIDC_CONFIGURATION_URL=https://authentik.yourdomain.com/application/o/mealie-demo/.well-known/openid-configuration
#      - OIDC_CLIENT_ID=Client Key
#      - OIDC_AUTO_REDIRECT=true
#      - OIDC_REMEMBER_ME=true
#      - OIDC_USER_GROUP=AppGroups
#      - OIDC_ADMIN_GROUP=authentik Admins
    env_file:
      - .env
    
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s