services:
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    container_name: wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=HiEKm6rdUfxz59
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=NfoSdkaavxR4C5
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
      - SYMFONY__ENV__FROM_EMAIL=mmcfetridg@ol.com
      - SYMFONY__ENV__DOMAIN_NAME=https://wall.mikemcfetridge.com
      - SYMFONY__ENV__SERVER_NAME="wallabag"
    ports:
      - "8667:80"
    volumes:
      - /home/miker/dockerapps/wallabag/images:/var/www/wallabag/web/assets/images
    depends_on:
      - db
      - redis
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=HiEKm6rdUfxz59
    volumes:
      - /home/miker/dockerapps/wallabag/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
  redis:
    image: redis:alpine
    restart: unless-stopped    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s