---
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest  # The Docker image to use.
    container_name: wireguard       # Name of the container.
    environment:                    # Environment variables to configure the ins>
      - LANG=en                     # Language settings.
      - WG_HOST=wireguard.mikemcfetridge.com      # Public IP or domain name whe>
      - PASSWORD=!Sucyetat123         # Password for accessing the WG-Easy web i>
      - PORT=51821                  # Port for the web interface.
      - WG_PORT=51820               # WireGuard port for VPN traffic.
    volumes:
      - ./data:/etc/wireguard   # Volume mapping for WireG>
    ports:
      - "51820:51820/udp"           # UDP port used by WireGuard.
      - "51821:51821/tcp"           # TCP port for accessing the web interface.
    cap_add:                        # Capabilities required for managing network>
      - NET_ADMIN
      - SYS_MODULE
    sysctls:                        # Kernel parameters that need to be set for >
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped         # Ensures the container restarts automatical>

# Network to join in docker which is named below
    networks:
      - proxy

# create PROXY network for NPM security. This will allow NPM to see and talk to >
networks:
  proxy:
    external: true
