services:
  # Resilio Sync - File Sync using BitTorrent Protocol
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - $RESILIOSYNC_PORT:8888
      - 55555:55555
    volumes:
      - $DOCKERDIR/appdata/resilio-sync/config:/config
      - $DOWNLOADSDIR:/downloads 
      - $DOCKERDIR/appdata/resilio-sync/data:/sync # Change $DOCKERDIR/appdata/resilio-sync/data to your data folder
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER