services:
  # pgAdmin - PostgreSQL Administration
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080:80"
    volumes:
      - ./appdata/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_ADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_ADMIN_PASSWORD

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
