services:
  # pgAdmin - PostgreSQL Administration
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$PGADMIN_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_ADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_ADMIN_PASSWORD
    # DOCKER-LABELS-PLACEHOLDER