services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-server
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npmuser1"                       # Change DB user name
      DB_MYSQL_PASSWORD: "Create Password"     # Change password and make it long and strong
      DB_MYSQL_NAME: "npm1"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'Create Password'   # Change root password and make it strong
      MYSQL_DATABASE: 'npm1'
      MYSQL_USER: 'npmuser1'                          # change username to match what you changed it to in above
      MYSQL_PASSWORD: 'Create Password'        # change password to match what you changed it to in above
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./npm/mysql:/var/lib/mysql
    
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s