services:
  # Node-RED - Programming for event-driven applications
  node-red:
    image: nodered/node-red
    container_name: node-red
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$NODERED_PORT:1880"
    volumes:
      - $DOCKERDIR/appdata/node-red:/data
    # DOCKER-LABELS-PLACEHOLDER