services:
  # cAdvisor - Container Advisor
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$CADVISOR_PORT:8080"
    # privileged: true # Only needed for CentOS, Fedora, Red Hat, etc.
    # devices:
    #   - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    # DOCKER-LABELS-PLACEHOLDER