services:
  # Open-WebUI - User-friendly AI Interface
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    networks:
      - default
    depends_on:
     - ollama
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://$SERVER_LAN_IP:$OLLAMA_PORT
      - WEBUI_SECRET_KEY=$OPENWEBUI_SECRET_KEY
      # - CORS_ALLOW_ORIGIN=
      - USER_AGENT=Open-WebUI
    volumes:
      - ./appdata/open-webui:/app/backend/data
 
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
