services:
  # Cloudflare Tunnel - Private Network over Internet
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command: tunnel run
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    devices:
      - /dev/net/tun
    volumes:
      - ./appdata/cloudflare-tunnel/hosts:/etc/hosts # Mount hosts file from host to container
      - /etc/localtime:/etc/localtime:ro  # Synchronize time with the host
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

