services:
  # Cloudflare DDNS - Dynamic DNS Updater
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./appdata/ddns-updater:/updater/data # Owned by UID 1000
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
      PERIOD: 12h
      UPDATE_COOLDOWN_PERIOD: 5m
      PUBLICIP_DNS_TIMEOUT: 3s
      HTTP_TIMEOUT: 10s
      # Web UI
      LISTENING_PORT: 8000
      # Backup
      BACKUP_PERIOD: 96h # 0 to disable
      BACKUP_DIRECTORY: /updater/data/backups
      # Other
      LOG_LEVEL: info
      # SHOUTRRR_ADDRESSES: $DISCORD_SHOUTRRR_ADDRESS

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s