services:
  # FileZilla - FTP Client
  filezilla:
    image: lscr.io/linuxserver/filezilla:latest
    container_name: filezilla
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined #optional
    restart: "unless-stopped"
    # DEVICES-GPU-PLACEHOLDER-DO-NOT-DELETE
    ports:
      - "3000:3000" # HTTP
      # - 3001:3001 # HTTPS
    volumes:
      - ./appdata/filezilla:/config
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
