services:
  # Navidrome - Music Server
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$NAVIDROME_PORT:4533"
    user: $PUID:$PGID
    volumes:
      - $DOCKERDIR/appdata/navidrome:/data
      # - $MEDIADIR1:/data/media1
      # - $MEDIADIR2:/data/media2
      # - $MEDIADIR3:/data/media3
    environment:
      - TZ=$TZ
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_REVERSEPROXYWHITELIST="0.0.0.0/0"
    # DOCKER-LABELS-PLACEHOLDER