services:
  # Remmina - Remote Desktop Client
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # DEVICES-GPU-PLACEHOLDER-DO-NOT-DELETE
    ports:
      - "3000:3000" 
      # - "3001:3001" # HTTPS
    volumes:
      - ./appdata/remmina:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      # DRINODE: /dev/dri/renderD128 
    
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s