services:
  # Gluetun - VPN Client for Docker Containers and More
  # Gluetun only for use by torrent clients + on demand lan devices.
  # Arr apps do not need VPN (not recommended), unless you have ISP/country restrictions.
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    # ports:
      # - $QBITTORRENTVPN_PORT:8080 # qBittorrent available at http://DOCKER-HOST-IP:$QBITTORRENTVPN_PORT
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun
    environment:
      TZ: $TZ
      VPN_SERVICE_PROVIDER: $GLUETUN_VPN_SERVICE_PROVIDER
      VPN_TYPE: $GLUETUN_VPN_TYPE # wireguard / openvpn
      # WIREGUARD_PRIVATE_KEY: $GLUETUN_WIREGUARD_PRIVATE_KEY
      # WIREGUARD_ADDRESSES: $GLUETUN_WIREGUARD_ADDRESSES
      # OPENVPN_USER: $GLUETUN_OPENVPN_USERNAME
      # OPENVPN_PASSWORD: $GLUETUN_OPENVPN_PASSWORD 
    # DOCKER-LABELS-PLACEHOLDER
