services:
  # Calibre - Ebook Manager
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "8080:8080" # Desktop GUI HTTP
      # - "8181:8181" # Desktop GUI HTTPS
      - "8081:8081" # Web Server GUI
    volumes:
      - ./appdata/calibre:/config
      - ./books:/data/books
      - ./comics:/data/comics
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      # PASSWORD: $CALIBRE_PASSWORD #optional
      # CLI_ARGS: #optional
    # Configure healthchecks

    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
