services:
  # Vaultwarden Password Manager
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$VAULTWARDEN_PORT:80"
    environment:
      # This is required to allow vaultwarden to verify the TLS certificate!
      - DOMAIN=https://SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1
      # - ADMIN_TOKEN=ADMIN-TOKEN-PLACEHOLDER
    volumes:
      - $DOCKERDIR/appdata/vaultwarden/data:/data
    # DOCKER-LABELS-PLACEHOLDER
