services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    restart: unless-stopped
    networks:
      - default
    ports:
      - ${FLOWISE_PORT}:${FLOWISE_PORT} # Default port is 5023
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLOWISE_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - $DOCKERDIR/appdata/flowise:/root/.flowise
    environment:
      - PORT=${FLOWISE_PORT}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - LOG_LEVEL=info
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=${POSTGRESQL_PORT}
      - DATABASE_NAME=flowise
      - DATABASE_USER=${FLOWISE_POSTGRESQL_USERNAME}
      - DATABASE_PASSWORD=${FLOWISE_POSTGRESQL_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_PATH=/root/.flowise/logs
      - STORAGE_TYPE=local
      - BLOB_STORAGE_PATH=/root/.flowise/storage
      - DEBUG=false
    # DOCKER-LABELS-PLACEHOLDER
