services:
  # Tailscale - Private Network over Internet
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    volumes:
      - $DOCKERDIR/appdata/tailscale:/var/lib/tailscale
    environment:
      - TS_AUTH_KEY=$TS_AUTH_KEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=false
    # DOCKER-LABELS-PLACEHOLDER
