---
services:
  app:
    container_name: portainer-agent
    deploy:
      mode: global
    image: docker.io/portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
