services:
  # Piwigo - Photo Management
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$PIWIGO_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/piwigo/config:/config
      - $DOCKERDIR/appdata/piwigo/gallery:/gallery
      - $PHOTOSDIR:/data/photos
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER