---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:2.0.8
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /AmberPRO/duplicati/config:/config
      - /Backups:/backups
      - /:/source
    ports:
      - 8200:8200
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s