services:
  # Jackett - Torrent proxy
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - default
    ports:
      - "$JACKETT_PORT:9117"
    volumes:
      - $DOCKERDIR/appdata/jackett:/config
      - $DOWNLOADSDIR:/data/downloads
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER