services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest"
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./netalert/config:/app/config
      - ./netalert/db:/app/db
      # (optional) useful for debugging if you have issues setting up the container
      - ./netalert/logs:/app/front/log
    environment:
      - TZ=America/New_York
      - PORT=20211

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s