services:
  # Wikidocs - Flat-file Markdown Wiki
  wikidocs:
    image: zavy86/wikidocs
    container_name: wikidocs
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - './appdata/wikidocs:/datasets'
    environment:
      PUID: 1000
      PGID: 1000

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
