services:
  # Wikidocs - Flat-file Markdown Wiki
  wikidocs:
    image: zavy86/wikidocs
    container_name: wikidocs
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks: 
      - default
    ports:
      - "$WIKIDOCS_PORT:80"
    volumes:
      - '$DOCKERDIR/appdata/wikidocs:/datasets'
    environment:
      PUID: $PUID
      PGID: $PGID
      # DOCKER-LABELS-PLACEHOLDER
