services:
  # Ollama - Local Open-source AI Models
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$OLLAMA_PORT:11434"
    volumes:
      - $DOCKERDIR/appdata/ollama:/root/.ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ['all']
    #           capabilities: [gpu]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    # DOCKER-LABELS-PLACEHOLDER
