services:
  # PrivateBin - Self-hosted Pastebin
  privatebin:
    image: privatebin/nginx-fpm-alpine
    container_name: privatebin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./appdata/privatebin/data:/srv/data # data volume for pastes allows pastes
      - ./appdata/privatebin/conf.php:/srv/cfg/conf.php:ro # second volume for custom configuration file
    environment:
      TZ: America/New_York
      
  # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s