services:
  # Jellyfin - Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    security_opt:
      - no-new-privileges:true
    restart: "no"
    user: 1000:1000
    # DEVICES-GPU-PLACEHOLDER-DO-NOT-DELETE
    ports:
      - "8096:8096"
    environment:
      UMASK_SET: 022
      TZ: America/New_York
    volumes:
      - ./appdata/jellyfin:/config
      - ./Downloads:/data/downloads
      # - $MEDIADIR1:/data/media1
      # - $MEDIADIR2:/data/media2
      # - $MEDIADIR3:/data/media3
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s