services:
  # Guacamole - Remote desktop, SSH, on Telnet on any HTML5 Browser
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole
      MYSQL_USER_FILE: /run/secrets/guac_mariadb_user
      MYSQL_PASSWORD_FILE: /run/secrets/guac_mariadb_password
    secrets:
      - guac_mariadb_user
      - guac_mariadb_password
    
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  guacd:
    image: guacamole/guacd
    container_name: guacd
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
        
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s