services:
  # ESPHome - Custom Smart Home with ESP Microcontrollers
  esphome:
    image: esphome/esphome
    container_name: esphome
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$ESPHOME_PORT:6052"
    volumes:  
      - $DOCKERDIR/appdata/esphome/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    # environment:
    #   - USERNAME=test
    #   - PASSWORD=ChangeMe
    # DOCKER-LABELS-PLACEHOLDER
